Pennsieve/pennsieve-app

src/components/datasets/settings/DatasetSettingsPublishing/StatusPublished.vue
Ported over a https://github.com/Pennsieve/pennsieve-app/pull/275 we did Nov 9, 20203.
Description
Remove changelog from settings page
Clickup Ticket
[Bug: Changelog file should not be overwritten but amended, listing all events in a chronological order](https://app.clickup.com/8664796/v/l/li/901101104468)
=> Remove changelog from settings page

src/components/welcome/DeveloperTools.vue, src/router/AboutPennsieve/AboutPennsieve.vue, src/router/index.js, src/router/welcomePage/WelcomePage.vue
- Adding page for developer-tools
- Adding page for Getting Help
Both pages fetch content from Readme.io and therefore are very simple to update at a later stage.
=> adding getting-help and developer-tools pages

src/components/shared/PennsieveHeader/contact-us-dialog/ContactUsDialog.vue
ticket: https://app.clickup.com/t/8687xqj98
bug fix - contact us dialog needed style changes
Files Changed
contact-us-dialog/ContactUsDialog.vue
notes: had to add an un-scoped style tag to reach the el-dialog element. not ideal way to do it, but might be a known bug in Element-Plus https://github.com/element-plus/element-plus/issues/5383 I've ran into it before but have not found a better solution.
=> Bug contact us

src/components/datasets/settings/DatasetSettingsContributors/ContributorRow/ContributorRow.vue, src/components/datasets/settings/DatasetSettingsContributors/DatasetSettingsContributors.vue, src/router/Dataset/SecondaryPageHeader.vue, src/store/index.js
- fixed the dataset contributors bug in dataset publishing page
- updated delete contributor code to fix a bug
- commented a method in secondaryheader to prevent existing runtime error 
[CLICKUP_TICKET](https://app.clickup.com/t/8687vr2x4)
_Delete those that don't apply._
- Reproduced the steps in the clickUp ticket recording of the bug. App is showing expected behavior after this fix
_Delete those that don't apply. Only apply the final commit message using the changelog when merging a feature to `DEVELOPMENT` that will be deployed to all users._
=> Fix publishing contributors options

src/components/datasets/DatasetPermissions/AddPermissionForm/AddPermissionForm.vue, src/components/datasets/collaborators/ConfirmRoleDialog/ConfirmRoleDialog.vue
BUG FIX
ticket
https://app.clickup.com/t/8687z9xff
small change to close ConfirmRoleDialog. No emit was being captured.
=> add close functionality to ConfirmRoleDialog

src/store/uploadModule.js
* Updated to use UUID v4 instead of v1 for uploads to match agent UUID generation
=> use uuid v4 instead of v1

src/components/Integrations/removeIntegrationDialog.vue, src/components/Publishing/DataUseAgreementSignDialog/DataUseAgreementSignDialog.vue, src/components/Publishing/PublishingDatasetListItemActions.vue, src/components/Publishing/RejectRequestDialog/RejectRequestDialog.vue, src/components/datasets/settings/DatasetSettingsContributors/ContributorDialog/ContributorDialog.vue, src/components/datasets/settings/DatasetSettingsContributors/DatasetSettingsContributors.vue, src/components/viewers/SlideViewer/SlideAnnotationDeleteDialog/SlideAnnotationDeleteDialog.vue, src/components/viewers/SlideViewer/SlideLayerDeleteDialog/SlideLayerDeleteDialog.vue, src/components/viewers/SlideViewer/SlideLayerDialog/SlideLayerDialog.vue
TICKET: https://app.clickup.com/t/86880en41
.sync used for two way binding is deprecated. emit('update:visible') >>> emit('close-dialog') for most cases.
=> update dialog close button to remove depricated sync binding

src/router/index.js
Request from users to match previous behaviour.
redirect https://app.pennsieve.io/{orgid}/datasets/{datasetId}
to https://app.pennsieve.io/{orgid}/datasets/{datasetId}/overview
=> redirect dataset url to dataset overview url

src/components/my-settings/MySettingsContainer.vue
Fix the Window Event Listener in **MySettingsContainer** - created in the `openORCID()` function - to send a slightly modified JSON payload to the Pennsieve API. The endpoint **POST** `/user/orcid` expects the payload to be:
```
{
"authorizationCode": {
"source": "orcid-redirect-response",
"code": authCode
}
}
```
The `authCode` is provided by ORCID after the user authenticates and authorizes access to their profile. This code is then used by the Pennsieve API to fetch an access token, which is stored on the user's Pennsieve User profile.
=> fix payload when linking orcid id to user profile

src/components/Publishing/PublishingProposalsList/PublishingProposalsList.vue, src/components/Publishing/PublishingProposalsList/PublishingProposalsListItem.vue
Fixed styling defects observed while testing. Made styling consistent with other tabs on 'Publishing' page
**Before:**
**After:**
=> fix styling defects in proposals tab

src/components/my-settings/MySettingsContainer.vue, src/site-config/dev.json, src/site-config/prod.json
This PR adds the ability to get the Pennsieve GitHub App URL from configuration. This change permits us to have different configuration for the Non-prod and Production environments. 
Tested locally running the Pennsieve App with: `npm run dev`
=> Get Pennsieve GitHub App URL from configuration

src/App.vue, src/main.js, src/mixins/global-message-handler/index.js, src/store/index.js
Handle direct linking when users change workspaces https://app.clickup.com/t/8688w1mkx 
This code is up in dev. To validate: 
1. Log in to Pennsieve
2. Copy a link to a dataset 
3. Switch to different org (not the org with the dataset you have the link copied for)
4. Copy the link into the browser
5. Validate that the link brings you directly to the dataset you are expecting and switches your org to the org associated with the linked dataset. 
Previous behavior before fix: User would be logged out if they tried to directly go to a linked dataset in an org other than the org they had selected.
=> Refactor data loading and fix direct linking 

src/components/datasets/settings/DatasetSettingsContributors/DatasetSettingsContributors.vue
When trying to add a contributor to a dataset on the Publishing page, it fails with an "undefined" error. 
The issue is that the **DatasetSettingsContributors** component is attempting to combine two objects using the `Ramda.merge()` function, but that function is not imported and was deprecated in v0.28 (see: https://github.com/ramda/ramda/releases/tag/v0.28.0).
Correction: use the `Ramda.mergeLeft()` function to combine the two objects.
[ClickUp ticket](https://app.clickup.com/t/86897e5ce)
=> Fix: add contributor to dataset

src/components/datasets/settings/DatasetSettingsContributors/DatasetSettingsContributors.vue
When trying to add a contributor to a dataset on the Publishing page, it fails with an "undefined" error.
The issue is that the DatasetSettingsContributors component is attempting to combine two objects using the Ramda.merge() function, but that function is not imported and was deprecated in v0.28 (see: https://github.com/ramda/ramda/releases/tag/v0.28.0).
Correction: use the Ramda.mergeLeft() function to combine the two objects.
[ClickUp ticket](https://app.clickup.com/t/86897e5ce)
=> (Deployment) Fix: add contributor to dataset

src/components/my-settings/MySettingsContainer.vue, src/components/releases/github-repos-list-item/gitHubReposListItem.vue, src/components/releases/github-repos-list/gitHubReposList.vue, src/components/releases/github-repositories/GitHubRepositories.vue, src/store/index.js, src/store/releasesModule.js
This PR includes the following changes:
- Created GitHub repos list and list item components and added to the GitHub repositories page
- Created releases module to handle GitHub service API Integration with the UI
- [Click Up link](https://app.clickup.com/t/8688z0xze)
=> Feature add GitHub releases route

src/components/bf-navigation/BfNavigationSecondary.vue, src/components/datasets/dataset-list/BfDatasetList.vue, src/components/datasets/dataset-list/dataset-list-item/BfDatasetListItem.vue
In this PR: 
- We don't need permissions on the metadata tab, I removed it. 
- I also formatted the code so this PR looks larger than it actually is. 
- Substantive changes are one line doing the permissions removal, and (unrelated to the metadata permissions removal) I hitchhiked a comment onto this PR to help other devs understand why we have a status indicator on the datasets page but more of the datasets you see in dev env are "No Status." In dev it looks broken, I tried to fix it, I realized it wasn't actually broken, the API just returns "No Status" a lot.🕵🏻 TLDR: it's because Sparc datasets have statuses in prod.
=> Remove unnecessary permissions on Metadata tab

src/components/datasets/files/BfDatasetFiles.vue
We didn't realize that these calls were necessary for infinite scroll functionality when we removed them here: 
https://github.com/Pennsieve/pennsieve-app/pull/184
I added them back in and commented that they are required for infinite scroll to avoid future confusion (they look to be duplicate if you don't realize the infinite scroll feature exists)
=> Fix infinite scroll

src/components/datasets/files/BfDatasetFiles.vue
prevents calls being made until the $route object is available to grab the fileId off of
=> Fix prevent calls with missing file

src/components/Analysis/Activity/ActivityMonitor.vue, src/components/Analysis/Activity/CustomNode.vue, src/components/Analysis/Activity/WorkflowsListItem.vue, src/components/datasets/files/RunAnalysisDialog/RunAnalysisDialog.vue, src/store/analysisModule.js
Code is currently up in dev. 
1.) Fetching Processor Status data in every 20 seconds - so when user is on the page they do not need to hard refresh to see statuses update. 
2.) Updated styling on statuses
STARTED:
https://github.com/user-attachments/assets/ae47908b-5d30-49ae-89a3-a936ae1e3687
SUCCEEDED
FAILED
NOT_STARTED
3.) Processor and Workflow selection and hover states updated for better user experience.
=> Processor Styling and Interval Fetch Updates for Activity Monitor 

src/components/Code/ConfigureRepo.vue, src/components/datasets/settings/BfPublishingSettings.vue, src/components/shared/ChecklistItem/ChecklistItem.vue
- fix ORCID link URL in dataset publishing page
- previous URL takes to internal route (doesn't exist anymore) in pennsieve app, new URL takes the user to the Profile page in Discover app
Recording of the fix
https://github.com/user-attachments/assets/d2b1fd51-5ac4-447f-94fe-a1dfc6bb3b7a
=> fix ORCID link URL in dataset publishing page

src/components/Code/ConfigureRepo.vue, src/components/datasets/settings/BfPublishingSettings.vue, src/components/shared/ChecklistItem/ChecklistItem.vue
- fix ORCID link URL in dataset publishing page
- previous URL takes to internal route (doesn't exist anymore) in pennsieve app, new URL takes the user to the Profile page in Discover app
Recording of the fix
https://github.com/user-attachments/assets/d2b1fd51-5ac4-447f-94fe-a1dfc6bb3b7a
=> fix ORCID link in dataset publishing page

src/router/Dataset/SecondaryPageHeader.vue, src/router/Dataset/SecondaryPageHeaderFiles.vue, src/router/index.js
reverted changes to SecondaryPageHeader.vue because it is used in several other places. I don't want to accidentally break something. 
new component: SecondaryPageHeader.vue 
Router:
add SecondaryPageHeader.vue to navigation
add variable and functionality to get and store last collection in navigation.
=> add global state for previous collection

src/router/Dataset/SecondaryPageHeaderFiles.vue, src/router/index.js
TICKET
https://app.clickup.com/t/86899pdc1
reverted changes to SecondaryPageHeader.vue because it is used in several other places. I don't want to accidentally break something.
new component: SecondaryPageHeader.vue
Router:
add SecondaryPageHeader.vue to navigation
add variable and functionality to get and store last collection in navigation.
=> add collections history to router

src/components/datasets/files/FileDetails/FileDetails.vue, src/components/viewer/ViewerPane/ViewerPane.vue
- hide timeseries viewer for unprocessed packages
https://github.com/user-attachments/assets/25542dd2-2eae-4510-9557-b6f443882c62
=> Fix update timeseries viewer availability

src/components/datasets/files/FileDetails/FileDetails.vue, src/components/viewer/ViewerPane/ViewerPane.vue
- hide timeseries viewer for unprocessed packages
https://github.com/user-attachments/assets/25542dd2-2eae-4510-9557-b6f443882c62
=> hide timeseries viewer for unprocessed packages
