- src/components/datasets/DatasetPermissions/AddPermissionForm/AddPermissionForm.vue
- src/components/datasets/settings/BfDatasetSettings.vue
- src/components/my-settings/MySettingsContainer.vue
- src/components/people/list/PeopleList.vue
- src/components/settings/OrgSettings.vue
- src/components/teams/list/TeamsList.vue
- src/routes/CreateOrg/CreateOrg.vue
- src/routes/Publishing/PublishingView.vue
- src/routes/index.js
- src/vuex/store.js
The purpose of this PR is to restrict access to certain parts of the platform for users who first sign up and are set to the default sandbox organization. Users would need to create an account in order to get access to the following features:
- People Page
- Teams Page
- Publishing Page
- Settings Page
- Within a dataset, the ability to add permissions if you have access
- Within a dataset, the ability to access the publishing tab
All but the last two will redirect to a create organization page. The button is not active yet, as I'm working on the create organization modal in another branch.
This is being pushed to a feature branch for now so as not to mess with the current functionality in dev while the backend is being worked on.
[CU-tq5m45](https://app.clickup.com/t/CU-tq5m45)
1. …
> Lock Down Org Features CU-tq5m45

- src/components/CreateOrganizationDialog/CreateOrganizationDialog.vue
- src/components/bf-navigation/UserMenu/UserMenu.vue
- src/routes/CreateOrg/CreateOrg.vue
The purpose of this PR is to add the Create New Organization modal in the restricted access page and in the organization menu. Please note that the backend isn't complete yet. 
[CU-tq5qjd](https://app.clickup.com/t/CU-tq5qjd)
1. Navigate to a restricted page and click on the `Create Organization` button. A modal to create an organization should come up (please note the `3 of 3 organizations remaining` text is static for now and will change when using backend data).
2. Play around with the form. When entering an org name and clicking `Create` a success toast should appear indicating that the org was created.
3. Click on `Create New Organization` from the user menu in the navigation bar. The same modal with functionality should appear.
> Create Organization Modal CU-tq5qjd

- src/components/notifications/Notifications.vue
The purpose of this PR is to fix a bug with the websocket closing too early. A dang overzealous watcher opening a new connection. We have the WS open when the `userToken` has been set (or changed) and it is always changing every four minutes now because that’s when we refresh the new Cognito token!
I added a check in this watcher to ensure we’re not closing the WS if it’s still open at this time.
N/A
- With the network tab open, log in to the app (or refresh just so you can see the WS connection to `wss://api.pennsieve.net/notifications/notification/connect` open
- Go to the tab where you can see the messages for this WS
- The websocket should stay open past four minutes.
> fix(Notifications): Fix issue with websocket closing too early

- src/components/datasets/DatasetPermissions/AddPermissionForm/AddPermissionForm.vue
- src/components/datasets/settings/BfDatasetSettings.vue
- src/components/people/list/PeopleList.vue
- src/components/settings/OrgSettings.vue
- src/components/teams/list/TeamsList.vue
- src/routes/Publishing/PublishingView.vue
- src/vuex/store.js
The purpose of this PR is to change the logic to use feature flag on org for restricted access. Users would need to create an account in order to get access to the following features:
- People Page
- Teams Page
- Publishing Page
- Settings Page
- Within a dataset, the ability to add permissions if you have access
- Within a dataset, the ability to access the publishing tab
- Navigate to the app and login as usual. 
- Using vue devtools, inspect `App` and enter the following in the console
```javascript
$vm0.$store.dispatch('updateActiveOrganization',  {
...$vm0.$store.state.activeOrganization,
organization: {
...$vm0.$store.state.activeOrganization.organization,
features: …
```
> Use feature flag on org for restricted access

- src/routes/CreateAccount/CreateAccount.vue
The purpose of this PR is to Fix links for terms and privacy on create user.
[tq54pk](https://app.clickup.com/t/tq54pk)
The terms and privacy links on the create account page should go to the Pennsieve docs.
> Fix links for terms and privacy on create user

- src/routes/CreateAccount/CreateAccount.vue
The purpose of this PR is to fix a race condition with reCAPTCHA badge on create account.
[tq5jj5](https://app.clickup.com/t/tq5jj5)
- Direct load the [create account](http://localhost:3000/sign-up) page
- The reCAPTCHA badge should show in the bottom left, and no console errors should appear.
- Hit the cancel button to go back to the login page
- Click on "Create one" to go to the create account page
- The reCAPTCHA badge should show in the bottom left, and no console errors should appear.
> Fix race condition with reCAPTCHA badge on create account

- src/components/app/App.vue
- src/components/app/app.js
- src/mixins/logout-handler/index.js
- src/vuex/store.js
The purpose of this PR is to fix an issue where the Link ORCID dialog is visible when it shouldn't be.
N/A
This can be done by inviting a new user and logging in to their account
- Log in to the app
- The link ORCID dialog should be visible
- Dimiss dialog
- Refresh app
- The link ORCID dialog should not be visible
- Log in to the app
- Using Devtools, change the value of the `user_token` to `123` (this is an invalid token)
- Refresh the app
- You should be logged out and the ORCID should not be visible
- Log in to the app
- The link ORCID dialog should not be visible
> fix(ORCID): Fix issue where ORCID dialog is visible when it should

- src/components/bf-navigation/UserMenu/UserMenu.vue
- src/mixins/global-message-handler/index.js
- src/routes/CreateOrg/CreateOrg.vue
The purpose of this PR is to add conditional logic to disable the `Create Organization` option from the User Menu and from the Restricted Access page once they have created three organizations. This will be pushed to a feature branch in the meantime so as not to interfere with the functionality on dev.
[CU-tq54pk](https://app.clickup.com/t/CU-tq54pk)
1. Log into the app and verify that you could click on the `Create Organization` menu item in the navigation bar user menu.
2. Using Vue Dev Tools, select `<App>` and in the console enter the following:
```
$vm0.$store.dispatch('updateProfile',  {
...$vm0.$store.state.profile,
maxOrganizationsAllowed: 3,
organizationsCreated: 3
}
)
```
The `Create Organization` menu item should now be disabled and not-clickable.
3. Navigate to a restricted …
> Conditional Logic to Disable Create Organization in User Menu CU-tq54pk

- src/routes/login/Login.vue
Until all demo organization features are done, we will just hide the create account link and then put it back later.
1. Navigate to the homepage
2. The `Create one here` link is no longer visible.
> Hide Create Account Link

- src/components/bf-navigation/BfNavigationSecondary.vue
- src/components/bf-navigation/UserMenu/UserMenu.vue
- src/components/bf-navigation/bf-navigation-item/BfNavigationItem.vue
- src/mixins/global-message-handler/index.js
- src/routes/CreateOrg/CreateOrg.vue
Features blocked:
- Call to get all organization users
- Permissions tab
- Disable create organization button when max organizations is reached for a user (This was here from before, not sure if we want to keep it in)
[u5da3b](https://app.clickup.com/t/u5da3b)
Get users in sandbox org:
The call to get org users happens during the login process without visual feedback, so to test that it is properly blocked, the devtools will be necessary.
1. Log out
2. Open the network tab in chrome devtools
3. Log in as a sandbox user
4. During the log in, verify that a call to `/organizations/{orgId}/members` is **not** made
5. Open the vue devtools
6. Select the vuex tab
7. In the state object, `orgMembers` should be an empty array `[]`
8. Log in as a non sandbox user
9. Repeat steps 2-7 but make sure …
> Add Sandbox Organization Blocks

- src/components/app/App.vue
- src/components/app/app.js
- src/components/datasets/dataset-list/BfDatasetList.vue
- src/components/onboarding-carousel/OnboardingCarousel.vue
- src/mixins/global-message-handler/index.js
- src/site-config/local.json
- src/vuex/store.js
Adjusted the Onboarding carousel and Link ORCID dialog to each display only once. The onboarding carousel will appear on initial log in, and must be completed to not be shown. The link ORCID dialog will appear if the onboarding carousel has been completed.
I had to do a funky workaround to allow the link ORCID dialog to actually be closed. The problem was that the `.sync` modifier on the dialog component is using a vuex state property (`isLinkOrcidDialogVisible`), which doesn't play nice with the `event-bus` event to update that value: `this.$emit('update:visible', false)`. I ended up creating a computed property to wrap `isLinkOrcidDialogVisible` and making custom `get()` and `set()` methods such that the event could actually change the value in the store. This seems to work quite well …
> Fix Onboarding Carousel and ORCID Signup bugs

- src/components/SandboxOrganizationBanner/SandboxOrganizationBanner.vue
- src/components/layout/BfPage/BfPage.vue
- src/routes/CreateOrg/CreateOrg.vue
Added a site-wide banner at the top of the page to notify sandbox users that they have restricted access. Also added a clickable link to open the intercom menu to request to create an organization.
[w1fg5m](https://app.clickup.com/t/w1fg5m)
1. Log in as a sandbox user.
2. The banner should be immediately visible at the top of the page.
3. Click on the "here" link.
4. The intercom window should open.
5. Close the intercom window.
6. Go to the people, teams, publishing, and my profile pages.
7. The banner should still be visible and the intercom link should work on all the above pages.
8. Log out and log back in as a non-sandbox user.
9. The banner should _not_ be visible.
> Sandbox User Notification Banner

- src/components/datasets/explore/LinkRecordMenu/LinkRecordMenu.vue
fix(metadata-records): Update link-records menu to always show "link files/folders" even if not record-relationships are defined for the model. 
Updated menu and checked:
1) render for records with no relationships defined in model
2) render for records with relationships in model
3) render for records with relationships in model but no records.
> enable select files/folders without model relationships

- src/assets/_variables.scss
- src/components/datasets/explore/ConceptInstance/ConceptInstance.vue
- src/components/datasets/explore/ConceptInstance/_concept-instance-static-property.scss
- src/components/datasets/explore/LinkRecordMenu/LinkRecordMenu.vue
other(model-service): Remove collapse menu for properties of a metadata record. Properties should always be visible and no need to add clutter with additional ways to collapse.
Visual inspection on local branch. 
This PR has no functional changes
> Link files menu

- src/components/datasets/explore/ConceptInstance/ConceptInstance.vue
- src/components/datasets/explore/ConceptInstance/ConceptInstanceStaticProperty.vue
- src/components/datasets/explore/ConceptInstance/_concept-instance-static-property.scss
[fix](Small fix to prevent incorrect rendering of properties in file-details page)
[style](updated style of file-details page to match metadata record details page.)
[style](Don't show source-files in file details when only a single source file exists)
[xqhrnm](https://app.clickup.com/t/xqhrnm)
Locally:
* Check file-details page
* Check record details page
*
> updated file-details page

- src/components/datasets/collaborators/DatasetCollaborator/DatasetCollaborator.vue
- src/components/datasets/settings/DatasetSettingsPublishing/DatasetSettingsPublishing.vue
- src/vuex/store.js
Updated front-end to allow superAdmins to change ownership of dataset if they have access to the dataset with any role.
User with superAdmin role logged in and switched ownership of dataset that user had access to without being owner.
Checked that user without superAdmin role cannot do this
> Switch owner by superadmin

- src/site-config/dev.json
- src/utils/aws-exports.js
This changes the AWS Cognito user pool that is used for authentication. Users will be transparently migrated from the old user pool to the new one upon logging in. This change is necessary to support federated login through ORCID.
Login multiple times with App and other service changes. Observe user is created in the new user pool -- migrated from the old user pool (user-migration trigger). Observe that `cognito_id` is updated in the `Pennsieve.Users` Postgres table (post-authentication trigger). Login is successful, all dataset and platform access is normal. 
_Delete those that don't apply. Only apply the final commit message using the changelog when merging a feature to `DEVELOPMENT` that will be …
> update AWS authentication to use new user pool and user/password flow

- src/components/Integrations/AddEditIntegrationDialog.vue
- src/components/datasets/DatasetActivity/DatasetActivityDetail/DatasetActivityDetail.vue
- src/utils/constants.js
Add new category for events when users manage integrations. CUSTOM events are triggered by the user by using the POST /dataset/<id>/event endpoint. Now, integrations can be configured to listen to those events. This can be leveraged by external platforms to send messages to other platforms in context of a dataset
[CLICKUP_TICKET](https://app.clickup.com/t/22gr4ex)
Locally created a new integration and selected to track CUSTOM events.
Using the swagger documentation, generated an event and:
1) Checked that the event shows up in the changelog
2) Checked that the event is pushed to the API endpoint described in the integration
_Delete those that don't apply. Only apply the final commit message using the changelog when merging a feature to `DEVELOPMENT` that …
> feat(integrations): Adding support for custom event tracking

- src/mixins/sanitize-name/index.js
- src/mixins/sanitize-name/sanitize-name.spec.js
Adds comma to the list of characters forbidden in a dataset name. Removes redundancy from regular expressions used to validate/sanitize dataset names.
[Include comma as invalid character in dataset name](https://app.clickup.com/t/2t8mcmd)
Added case to existing unit test.
> Forbid commas in dataset names

- src/components/shared/BfLogInDialog/BfLogInDialog.vue
When a user successfully authenticates, the `isLoggingIn` flag is cleared (making the Sign In button clickable) and the Login dialog is closed. In addition, a 'toast' message is sent indicating that authentication was successful and letting the users know that the workspace is being loaded.
[Improve Responsiveness of the Pennsieve Login Experience](https://app.clickup.com/t/2w40ufb)
locally
> Improve user login experience

- src/components/shared/BfLogInDialog/BfLogInDialog.vue
If the username or password is incorrect, then authentication with Cognito will fail. The user is notified of the authentication failure by a specific 'toast' message. In this case, the password field of the login is cleared and the dialog is not closed -- this provides the user the ability to type the password again, without having to click "login" and re-enter the username.
_Delete those that don't apply. Only apply the final commit message using the changelog when merging a feature to `DEVELOPMENT` that will be deployed to all …
> fix: don't close login dialog on authentication failure

- src/components/DeletedFiles/DeletedFiles.vue
Updated the code so we are sending the `datasetId` instead of the `fileId` when the restore endpoint is called in all cases. 
Previously we were sending `datasetId` when restore was called on the main files page (`dataset-files` route) and the `fileId` on all other routes (which included when the endpoint was called when the user is interacting with the undelete modal). I removed this so now we are always sending the datasetId to the restore endpoint. 
Tested undelete functionality locally after the change and it is working as expected.
> BUG: Restore Request Sending Wrong Dataset ID

- src/components/shared/bf-rafter/BfRafter.vue
Hotfix for changing rafter labeling to accurately indicate that user is navigating back to a files list from a file record.
[[CLICKUP_TICKET](https://app.clickup.com/t/CLICKUP_TICKET)](https://app.clickup.com/t/862jw3emn)
- [ x ] Bug fix (non-breaking change which fixes an issue)
tested locally to verify that it handles records and files cases
> hotfix for labeling while navigating back to files from record

- src/components/datasets/files/BreadcrumbNavigation/BreadcrumbNavigation.vue
Hotfix for file path and breadcrumb reverse order bug
https://app.clickup.com/t/862jyaumz,
https://app.clickup.com/t/862jyaufk
- [ x] Bug fix (non-breaking change which fixes an issue)
tested locally. Please use http://localhost:3000/N:organization:050fae39-4412-43ef-a514-703ed8e299d5/datasets/N:dataset:f2d05e00-ee16-41b3-8352-157d6c4c2d19/overview to test functionality.
> file path fix

- src/components/datasets/DatasetOverview/DatasetOverview.vue
This PR makes it so users can edit the Changelog field at /overview on dataset when the dataset is NOT locked. When the dataset IS locked, only users who are publishers will be able to edit it at /overview. 
[Changelog - enable publisher's editing abilities](https://app.clickup.com/t/85zt98bbk)
locally - going to test the whole feature (FE and BE) with Edmore in dev.
> Make changelog field on Overview view editable

- src/components/Integrations/AddEditIntegrationDialog.vue
- src/components/Integrations/IntegrationsList/IntegrationsList.vue
- src/components/datasets/files/custom-actions-dialog/CustomActionsDialog.vue
This adds the ability to specify a target directory when users are running an application on target folders/files. 
Payload I am now passing to /integrations endpoint:
`{"applicationId":82,"datasetId":"N:dataset:e2eaa76a-e0e0-4f25-97a8-6fa2bf6dd83f","packageIds":[],"params":{"target_path":"target/path/to/file"}}` 
There is currently no validation on what the FE will allow for the target path - we should discuss validation for a future enhancement - it would be a good idea to add validation on the nested path format to avoid user issues with specifying the path to the target directory. 
[AppStore: Enable users to define a target directory when they run an application (frontend)](https://app.clickup.com/t/8686wy8yj)
Tested Locally
> AppStore: Enable users to define a target directory when they run an application (frontend)
