src/components/bf-navigation-tertiary/BfNavigationTertiary.vue
src/components/bf-navigation/create-button/CreateButton.vue
src/components/bf-navigation/create-button/CreateButtonWorkspace.vue
src/components/datasets/DatasetPermissions/AddPermissionForm/AddPermissionForm.vue
src/components/datasets/explore/ConceptInstance/ConceptInstance.vue
src/components/datasets/explore/ConceptInstance/RelationshipsTable.vue
src/components/datasets/explore/search/ConceptSearch.vue
src/components/people/list/PeopleList.vue
src/routes/datasets/Datasets.vue

Removing logic that checks for clinical trial management

Remove logic around clinical management feature flag

---

src/routes/CreateAccount/CreateAccount.vue

The purpose of this PR is to fix the endpoint for the sign-up form to include `/account`
Correct endpoint should be called as expected.

Create Account Endpoint Fix

---

src/components/FinalizeAccount/FinalizeAccount.vue
src/components/app/app.js
src/main.js
src/mixins/global-message-handler/index.js
src/mixins/request/index.js
src/mixins/request/request.spec.js
src/routes/index.js
src/routes/login/Login.vue
src/routes/welcome/Welcome.vue

* Added a route for verifying accounts that were created by the user without an invite
* Updated password validation logic to ensure password and verified password are the same.
1. Ran locally and created account
2. Took the link from email and used  the form locally to set password
3. Was able to login
4. Checked a number of password scenarios
- password is too short
- passwords don't match

updated createAccount flow

---

CHANGELOG.md
package.json
src/components/FilesTable/FilesTable.vue
src/components/TableMenu/TableMenu.vue
src/components/datasets/files/BfDatasetFiles.vue

[feature](Adding support to get long-lasting presigned url in app)
[ydgmbm](https://app.clickup.com/t/ydgmbm)
This was tested by running the app locally, and requesting the link for a number of files.

Presigned url

---

package.json
src/components/shared/Accordion/Accordion.vue
src/components/viewer/BfViewerSidePanel/BfViewerSidePanel.vue
src/components/viewer/palettes/PaletteAnnotations/AnnotationGroup.vue
src/components/viewer/palettes/PaletteAnnotations/PaletteAnnotations.vue
src/components/viewer/palettes/PaletteAnnotations/TSAnnotation.vue
src/components/viewer/palettes/PaletteChannels/PaletteChannels.vue
src/components/viewers/TSViewer/TSAnnotationCanvas.vue
src/components/viewers/TSViewer/TSAnnotationDeleteDialog/TsAnnotationDeleteDialog.vue
src/components/viewers/TSViewer/TSAnnotationModal.vue
src/components/viewers/TSViewer/TSFilterModal.vue
src/components/viewers/TSViewer/TSPlotCanvas.vue
src/components/viewers/TSViewer/TSScrubber.vue
src/components/viewers/TSViewer/TSViewer.vue
src/components/viewers/TSViewer/TSViewerCanvas.vue
src/main.js
src/mixins/ts-annotation/index.js
src/vuex/modules/viewer.js
web-components/src/components/blackfynn/viewers2/timeseries/canvas/viewer.html
yarn.lock

Updated timeseries viewer to support creation and navigation through annotations.

Feat ts annotations

---

.gitignore
src/components/Integrations/AddEditIntegrationDialog.vue
src/components/Integrations/IntegrationsList/IntegrationsList.vue
src/components/Integrations/integration-list-item/IntegrationListItem.vue
src/vuex/modules/integrationsModule.js

* added front-end mechanism to edit integrations

edit integrations

---

src/components/Integrations/IntegrationsList/IntegrationsList.vue

small fix to sync integrationEdit object

sync editIntegration var

---

src/mixins/global-message-handler/index.js
src/routes/login/Login.vue

on logout, clear state and remove user_token before calling Auth.signOut()
on a federated login, Auth / Cognito will redirect and the call which clears state and removes the user_token is not called unless the user clicks "sign out" twice

Login to pennsieve with orcid - some minor changes

---

CHANGELOG.md
src/routes/login/Login.vue
src/site-config/prod.json

- Update `prod.json` with authentication settings for new Cognito User Pool
- comment out "Login with ORCiD" button
[Deploy Authentication using new/updated Infrastructure to Production](https://app.clickup.com/t/22pcyk4)
This has been tested in DEV environment.

Prod deploy cognito user migration

---

src/components/Integrations/AddEditIntegrationDialog.vue
src/components/Integrations/IntegrationsList/IntegrationsList.vue
src/components/Integrations/integrationApiKeyDetails.vue
src/vuex/modules/integrationsModule.js

[22gr4re](https://app.clickup.com/t/22gr4re)
* Ran locally and created and deleted integrations
* Tested if the provided api key/secret allow me to access the datasets that have the integration enabled

Added api key info for create integration

---

src/routes/login/Login.vue

This change fixes two small typos on the landing page.

Fix landing page typos

---

CHANGELOG.md
package.json

Updated the version number and changelog.

Version and CHANGELOG.md update for release of typos fix

---

src/components/shared/BfLogInDialog/BfLogInDialog.vue
src/utils/aws-exports.js

Incorporated changes into the newly revised landing/login pages to support Federated Login with ORCID iD. 
[CLICKUP_TICKET](https://app.clickup.com/t/21zg41y)
locally

Adapt updated login to support login with orcid

---

src/site-config/prod.json

Update prod ORCID APP ID

---

package.json
src/components/shared/BfLogInDialog/BfLogInDialog.vue
src/routes/login/Login.vue

Sign up with orcid

---

src/components/ORCID/ORCIDRedirect.vue
src/components/SetupFederatedLogin/SetupFederatedLogin.vue
src/components/SetupProfile/SetupProfile.vue
src/components/my-settings/MySettingsContainer.vue
src/components/shared/BfLogInDialog/BfLogInDialog.vue
src/mixins/global-message-handler/index.js
src/routes/index.js
src/site-config/dev.json
src/site-config/prod.json
src/vuex/store.js

Web app component to ask user to provide an email address upon logging in with ORCID iD that is not linked to an existing account. If the email is not known, update the new account (Pennsieve and Cognito) with the email address. If the email is known (i.e., associated with an existing Pennsieve account) then give the option to link the accounts.
[CLICKUP_TICKET](https://app.clickup.com/t/2g97eqa)
Locally, and (eventually) in the Non-prod environment.

App: Merge ORCID and Pennsieve user accounts - part 1

---

src/components/SetupFederatedLogin/SetupFederatedLogin.vue

SetupFederatedLogin: clean up log and error messages, simplify code flow
- clean up log and error messages
- simplify code flow
locally

App: Merge ORCID and Pennsieve user accounts - part 3

---

src/components/settings/OrgSettingsDataUseAgreements/OrgSettingsDataUseAgreements.vue
src/components/shared/DataUseAgreementDialog/DataUseAgreementDialog.vue

- show formatted Markdown in Data Use Agreement dialog
locally

App: Data Use Agreement fixes

---

src/components/SetupFederatedLogin/SetupFederatedLogin.vue

App: Orcid sign up loose ends

---

src/components/SetupFederatedLogin/SetupFederatedLogin.vue

SetupFederatedAccount: include password in /merge request in order to pass it on to the new Cognito user

App: tidy up a few final ORCID login loose ends

---

src/components/bf-navigation/bf-navigation-item/BfNavigationItem.vue
src/components/datasets/DatasetActivity/UploadManifest/UploadManifest.vue
src/components/datasets/DatasetActivity/UploadManifestFiles/ManifestFileFilterMenu.vue
src/components/datasets/DatasetActivity/UploadManifestFiles/UploadManifestFile.vue
src/components/datasets/DatasetActivity/UploadManifestFiles/UploadManifestFiles.vue

1. Added support to refresh manifest files list
2. Update status that user can select for filtering

Manifest refresh and status updates

---

src/components/my-settings/MySettingsContainer.vue
src/components/my-settings/windows/DeleteOrcid.vue

small change to exit out of unlink orcid dialog

---

src/components/my-settings/MySettingsContainer.vue
src/routes/ResetPassword/ResetPassword.vue

Frontend change for email update. On email change in settings page, the app will communicate with cognito and change the users email address with their profile.
[CLICKUP_TICKET]
https://app.clickup.com/t/2w40wuv
- [ x] New feature (non-breaking change which adds functionality)
ran locally

Email update

---

src/components/my-settings/MySettingsContainer.vue

The User Update Request was extended to include a flag that indicates whether the change was user initiated. This is checked in the "change email address" path and controls whether an email is sent to the user summarizing the change.

fix: include userRequestedChange on email change

---

src/components/people/windows/InviteMember.vue

allow the inviting user to provide a custom message on workspace invite, which is sent in the email to the invitee

App: allow custom message on workspace invite

---

src/components/welcome/request-survey/ProposalContributor.vue
src/components/welcome/request-survey/ProposalContributorDialog.vue
src/components/welcome/request-survey/RequestSurvey.vue
src/vuex/modules/repositoryModule.js

Dataset proposal contributors

---

src/assets/_list-item.scss
src/components/Publishing/PublishingProposalsList/PublishingProposalsList.vue
src/components/Publishing/PublishingProposalsList/PublishingProposalsListItem.vue
src/components/welcome/SubmitDatasets.vue
src/components/welcome/Welcome.vue
src/components/welcome/repository-info/RepositoryInfo.vue
src/components/welcome/repository-list-item/repositoryListItem.vue
src/components/welcome/request-list-item/RequestListItem.vue
src/components/welcome/request-survey/ProposalContributor.vue
src/components/welcome/request-survey/RepoSelector.vue
src/components/welcome/request-survey/RequestSurvey.vue
src/routes/Publishing/PublishingView.vue
src/routes/index.js
src/utils/constants.js
src/vuex/modules/publishingModule.js
src/vuex/modules/repositoryModule.js

Publisher view of proposals

---

src/components/DeletedFiles/DeletedFiles.vue
src/components/datasets/files/BreadcrumbNavigation/BreadcrumbNavigation.vue
src/components/datasets/files/Metadata/FileMetadataInfo.vue
src/components/datasets/files/bf-upload-menu/BfUploadMenu.vue
src/components/shared/bf-rafter/BfRafter.vue

- moved undelete button from header to side panel
- added some warning text in undelete modal regarding permanently deleting items after 30 days
- updated "add file" button color
There are a lot of lint changes staged in this PR because I used prettier for linting (including the .prettierrc in the codebase). Unfortunately, this makes this PR difficult to review because there are so many lint changes - however, going forward, this will make it easier to work in these files so I left the lint changes in. 
I don't think there is one
Locally checked UI in a variety of data scenarios 

moved undelete button and changed Add File button color

---

src/components/DeletedFiles/DeletedFiles.vue
src/components/shared/bf-dialog/bf-dialog.vue

https://app.clickup.com/t/860qh0gae
tested a few different data scenarios 

added a flag for a larger modal and updated styles

---

src/components/Publishing/PublishingProposalsList/PublishingProposalsList.vue
src/components/welcome/Info.vue
src/components/welcome/request-list-item/RequestListItem.vue
src/components/welcome/request-survey/RequestSurvey.vue
src/vuex/modules/repositoryModule.js

Implemented the following capability:
- Load "More Information" page items from S3
Fixed the following items:
- close Request Form when Accept or Reject is confirmed
- don't permit Submit Request until form is considered complete
- prevent special characters in Dataset Proposal name
- [Load "More Information" page items from S3](https://app.clickup.com/t/860qqwwwv)
- [BUG: close Request Form when Accept or Reject is confirmed](https://app.clickup.com/t/860qq29wk)
- [BUG: don't permit Submit Request until form is considered complete](https://app.clickup.com/t/860qqe86a)
- [BUG: prevent special characters in Dataset Proposal name](https://app.clickup.com/t/860qq29qd)
Tested locally
_Delete those that don't apply. Only apply the final commit message using the …

Fix dataset proposal items

---

src/components/datasets/DatasetActivity/DatasetManifests.vue
src/components/datasets/explore/DataModelGraph.vue
src/components/datasets/explore/search/ModelRecords.vue
src/vuex/modules/datasetModule.js

* fix for empty and loading state in Manifest page
* Small styling updates in records page

fix for empty manifest and small styling changes

---

src/assets/_base.scss
src/components/app/App.vue
src/components/datasets/DatasetOverview/DatasetOverview.vue
src/components/datasets/settings/BfPublishingSettings.vue
src/components/datasets/settings/DatasetIntegrationsSettings.vue
src/components/shared/ChecklistItem/ChecklistItem.vue
src/components/shared/bf-rafter/BfRafter.vue
src/mixins/global-message-handler/index.js
src/routes/index.js

resolve prod merge conflicts -> main

---

src/components/DeletedFiles/DeletedFiles.vue

add some info text warning users about delay between delete and restore 

---

src/main.js

hotfix for this user reported issue: https://app.clickup.com/t/85zt5bxc4

added route name to allowList

---

src/components/Publishing/PublishingProposalsList/PublishingProposalsList.vue
src/components/welcome/SubmitDatasets.vue
src/components/welcome/request-list-item/RequestListItem.vue
src/components/welcome/request-survey/RequestSurvey.vue
src/vuex/modules/repositoryModule.js

- add image to empty list for dataset proposals
- make "New Request" a link in the text of the empty list
- remove RepositoryId from Repositories and Dataset Proposals

Publishing dataset proposal changes

---

.github/workflows/release.yml
Jenkinsfile

Updating Jenkinsfile to build and deploy on push to main and on tag release
[[CLICKUP_TICKET](https://app.clickup.com/t/CLICKUP_TICKET)](https://app.clickup.com/t/85zt4p4c8)
- [ x ] New feature (non-breaking change which adds functionality)
Need merged into main to test

Deploy from tag release

---

src/components/Integrations/AddEditIntegrationDialog.vue
src/components/Integrations/IntegrationsList/IntegrationsList.vue
src/components/Integrations/applicationsList/ApplicationsList.vue
src/components/Integrations/integration-list-item/IntegrationListItem.vue
src/components/bf-navigation/BfNavigation.vue
src/components/datasets/settings/DatasetIntegrationsSettings.vue
src/main.js
src/mixins/FileTypeMapper/index.js
src/routes/Integrations/Integrations.vue
src/routes/index.js

Enable users to create applications and separate them in the web-app from webhooks.

Separate App from Webhook integrations

---

src/components/datasets/files/custom-actions-dialog/CustomActionsDialog.vue

Fixed URL to be dynamic
Added an error state so the dialog closes when you get an API error 
https://app.clickup.com/t/86857qff0
locally, on the web app UI

Some updates for the custom actions dialog 

---

src/components/datasets/files/custom-actions-dialog/CustomActionsDialog.vue

Testing the cytof pipeline FE integration

trouble shooting FE integration

---

src/components/datasets/files/custom-actions-dialog/CustomActionsDialog.vue

Updated payload for POST to /integrations 
https://app.clickup.com/t/86857qb3d

Change payload for Applications feature 

---

src/components/datasets/DatasetOverview/DatasetOverview.vue
src/components/datasets/files/bf-delete-dialog/BfDeleteDialog.vue
src/components/datasets/settings/BfPublishingSettings.vue
src/components/datasets/settings/DatasetSettingsPublishing/OwnerOrcid.vue
src/components/shared/bf-dialog-header/BfDialogHeader.vue

This is a deployment PR for three features: 
1. Bug: Dataset overview checklist does not update properly for ORCiD id - [https://app.clickup.com/t/85zt98bbk](https://app.clickup.com/t/85zt98bbk)
2. Changelog - enable publisher's editing abilities [https://app.clickup.com/t/85zt98bbk](https://app.clickup.com/t/85zt98bbk)
3. Change close modal "x" to color white [https://app.clickup.com/t/86851n1z6](https://app.clickup.com/t/86851n1z6)
see above 
Deployment 
I ran PROD branch locally and validated each feature was working

Deployment 

---

src/components/SetupProfile/SetupProfile.vue
src/main.js
src/routes/index.js

- add a new route for external/guest users to complete their sign up
- re-work the SetupProfile component/form to handle external/guest user sign up
locally

Fix for External/Guest user sign up

---

src/components/bf-navigation/UserMenu/UserMenu.vue

Update to add terms of use for NIH

add NIH terms of use

---

src/components/datasets/settings/DatasetSettingsPublishing/StatusPublished.vue

Description
Remove changelog from settings page
Clickup Ticket
[Bug: Changelog file should not be overwritten but amended, listing all events in a chronological order](https://app.clickup.com/8664796/v/l/li/901101104468)
Type of change
Delete those that don't apply.
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update
How Has This Been Tested?
locally validated that the settings page now does not have the changelog

Bug: Remove changelog from settings page

---

src/components/datasets/settings/DatasetSettingsPublishing/StatusPublished.vue

Remove changelog from settings page
[Bug: Changelog file should not be overwritten but amended, listing all events in a chronological order](https://app.clickup.com/8664796/v/l/li/901101104468)
locally validated that the settings page now does not have the changelog

Remove changelog from settings page

---

src/components/Integrations/applicationsList/ApplicationsList.vue

This PR contains some lint changes and I also removed the check that requires users to be an admin to add an app. 
[FE enhancements to support App Store for Hackathon](https://app.clickup.com/t/8686bp5u5)
Locally

remove requirement to be an admin to add Apps

---

src/components/Integrations/AddEditIntegrationDialog.vue
src/components/Integrations/applicationsList/ApplicationsList.vue

lint changes and removed some validation on form that isn't working correctly. 
[FE enhancements to support App Store for Hackathon](https://app.clickup.com/t/8686bp5u5)

Removed validation that is causing bug on form 

---

index.html
src/components/BfUpload/BfUpload.vue
src/components/SandboxOrganizationBanner/SandboxOrganizationBanner.vue
src/components/analytics/Analytics.spec_not_used.js
src/components/analytics/Analytics.vue
src/components/bf-navigation/HelpMenu/HelpMenu.vue
src/components/bf-navigation/UserMenu/UserMenu.vue
src/components/bf-navigation/create-button/CreateButton.vue
src/components/datasets/LockedBanner/LockedBanner.vue
src/components/datasets/dataset-list/dataset-list-item/BfDatasetListItem.vue
src/components/datasets/settings/BfDatasetSettings.vue
src/main.js
src/mixins/logout-handler/logout.spec.js
src/routes/CreateAccount/CreateAccount.vue
src/routes/CreateOrg/CreateOrg.vue

1. Added a link in the "Get Help" menu to the Pennsieve open office hours link:
[pennsieve-open-office-hours](https://docs.pennsieve.io/docs/pennsieve-open-office-hours)
2. Added the contact form link under "Contact Us" in the "Get Help" menu: 
3. Removed all references to intercom
Please note there are also lint changes staged. 
[Update Pennsieve Platform Homepage and Login Interface with Contact Us form to replace Intercom](https://app.clickup.com/t/8686g7k81)
[Update Pennsieve Platform with Office Hours Information](https://app.clickup.com/t/8686g7pme)
Tested and validated lcoally

Add contact form and office hours information to Pennsieve 

---

src/components/datasets/files/custom-actions-dialog/CustomActionsDialog.vue

Fix issue where downdown items are missing 
[Fix issue where downdown items are missing ](https://app.clickup.com/t/8686rby4q)
tested locally

fix for missing dropdown options and undefined values
