package-lock.json
package.json
src/App.vue
src/main.js
src/router/CreateAccount/CreateAccount.vue

Sign-up component now fully migrated, and sign-up functionality working.
https://github.com/Pennsieve/pennsieve-app-2/assets/4977875/3befa405-a490-4e9f-9455-eef5f331b951
Let me know if we need to get the Recaptcha badge off the main page - google in includes it there by default and it's good practice to link users to the terms of service since they are being tracked by Recaptcha v3 not just on forms but on the main page as well to check to see if they are human (bottom right of screenshot - I moved it from bottom left because it was blocking terms of service link).

sign-up now working

---

src/components/bf-navigation/BfNavigation.vue

* Added the ORGIDs for SPARC and Immune Health to trigger custom themes

trigger custom theme for sparc and IH

---

src/components/DeletedFiles/DeletedFiles.vue
src/components/FilesTable/FilesTable.vue
src/components/datasets/files/BfDatasetFiles.vue
src/components/datasets/files/custom-actions-dialog/CustomActionsDialog.vue

This PR gets the custom actions and undelete modals working and styled. 
There are a lot of lint changes - I plan to run the linter over every file in the codebase when I have the time, so we can avoid these types of lint-change heavy PR's going forward and have standardized linting aligned with what is defined in the lint config for the project. 
Let's skip merging this to dev env separately this time, I will just sync up dev and main once this is merged (I tested locally)
https://github.com/Pennsieve/pennsieve-app-2/assets/4977875/84ce47f9-830b-47f8-8c1c-27c51a0840a1

Functionality and Styling for App Store and Undelete 

---

src/components/datasets/settings/DatasetSettingsPublishing/OwnerOrcid.vue
src/components/my-settings/MySettingsContainer.vue
src/store/index.js

Ported over this code [https://github.com/Pennsieve/pennsieve-app/pull/281/files](https://github.com/Pennsieve/pennsieve-app/pull/281/files) from pennsieve-app

added update orcid on publish feature

---

index.html
src/components/BfUpload/BfUpload.vue
src/components/PennsieveUpload/PennsieveUpload.vue
src/components/PennsieveUpload/PsUploadFile.vue
src/components/datasets/files/BfDatasetFiles.vue
src/components/shared/bf-rafter/BfRafter.vue
src/main.js
src/router/Datasets/Datasets.vue
src/router/index.js
src/site-config/dev.json
src/site-config/prod.json
src/store/datasetModule.js
src/store/uploadModule.js

Integrating push notifications through Pusher for uploads. 
Web-app automatically refreshes file-list when new files are uploaded and notifies the users the upload is complete.
https://github.com/Pennsieve/pennsieve-app-2/assets/1605953/c36b6d17-8316-4614-937a-1d295ea66328

pusher upload updates

---

index.html
src/components/BfUpload/BfUpload.vue
src/components/PennsieveUpload/PennsieveUpload.vue
src/components/PennsieveUpload/PsUploadFile.vue
src/components/datasets/files/BfDatasetFiles.vue
src/components/shared/bf-rafter/BfRafter.vue
src/main.js
src/router/Datasets/Datasets.vue
src/router/index.js
src/site-config/dev.json
src/site-config/prod.json
src/store/datasetModule.js
src/store/uploadModule.js

Reverts Pennsieve/pennsieve-app-2#24

Revert "pusher upload updates"

---

index.html
src/components/BfUpload/BfUpload.vue
src/components/PennsieveUpload/PennsieveUpload.vue
src/components/PennsieveUpload/PsUploadFile.vue
src/components/datasets/files/BfDatasetFiles.vue
src/components/shared/bf-rafter/BfRafter.vue
src/main.js
src/router/Datasets/Datasets.vue
src/router/index.js
src/site-config/dev.json
src/site-config/prod.json
src/store/datasetModule.js
src/store/uploadModule.js

Reverts Pennsieve/pennsieve-app-2#25

Revert "Revert "pusher upload updates""

---

src/components/welcome/DeveloperTools.vue
src/router/AboutPennsieve/AboutPennsieve.vue
src/router/index.js
src/router/welcomePage/WelcomePage.vue

Test if this works --- Just changed the name of the branch but is same code as other dev tools merge request.

adding getting-help and developer-tools pages

---

src/components/datasets/files/BfDatasetFiles.vue

added max height back in 
https://github.com/Pennsieve/pennsieve-app-2/assets/4977875/962a5662-f2bb-4353-b664-e08adf9e0a87

Fix Infinite Scroll Feature 

---

src/components/Publishing/PublishedDatasetListItem/PublishedDatasetListItem.vue

https://app.clickup.com/t/8687yzm7p
-change routeName back to 'dataset-overview'

change route name back to dataset-overview

---

Jenkinsfile
README.md
src/components/FilesTable/FilesTable.vue
src/components/TableMenu/TableMenu.vue
src/components/datasets/files/BfDatasetFiles.vue
src/components/shared/ReleaseBanner/ReleaseBanner.vue
src/components/shared/readme-doc/ReadmeDoc.vue
yarn.lock

* Fix "Open with Office 365" in table menu
* Fix other actions in Table menu
* Fix select row in file browser

Feature smal fixes

---

src/components/Publishing/PublishingDatasetListItemActions.vue
src/components/Publishing/RejectRequestDialog/RejectRequestDialog.vue

ticket:https://app.clickup.com/t/8688372zq
RejectRequestDialog needed to be fixed for vue 3

migrate rejectrequestdialog to vue3 and fix close functionality

---

src/components/bf-navigation/BfNavigation.vue
src/mixins/custom-theme/index.js

* Updated the logo for the Immune Health Space
* Updated the colors for Immune Health Space

updated branding

---

src/components/datasets/settings/DatasetSettingsPublishing/DatasetSettingsPublishing.vue

https://app.clickup.com/t/8688fvb3f

Hot fix to only enable Request to Publish button for dataset owners

---

src/components/my-settings/MySettingsContainer.vue

Reverts Pennsieve/pennsieve-app#92

Revert "fix payload when linking orcid id to user profile"

---

src/components/people/list/PeopleList.vue

Vue3 People, Teams need to be ordered A to Z by default https://app.clickup.com/t/8688myhu1

Vue3 People, Teams need to be ordered A to Z by default

---

src/components/Publishing/PublishingProposalsList/PublishingProposalsList.vue
src/store/publishingModule.js

- fix datasets not displayed in 'proposed' datasets tab in the publishing section of the workspace
https://github.com/Pennsieve/pennsieve-app/assets/160671504/0a9b27a7-4160-4a7d-bb8c-c71584a1b639

fix proposed datasets error

---

package-lock.json
package.json
src/components/FinalizeAccount/FinalizeAccount.vue
src/components/SetupFederatedLogin/SetupFederatedLogin.vue
src/components/SetupProfile/SetupProfile.vue
src/components/shared/PsLoginDialog/PsLogInDialog.vue
src/router/ResetPassword/ResetPassword.vue

Add View/Hide feature for all the password input elements
view-password
hide-password

Feature upgrade password input box

---

src/components/Publishing/PublishingProposalsList/PublishingProposalsListItem.vue

Proposed Datasets Actions Not Fully Migrated https://app.clickup.com/t/8688wdt1n

Proposed Datasets Actions Not Fully Migrated

---

src/App.vue
src/components/shared/AnnouncementBanner/AnnouncementBanner.vue

Banner component now accepts props for copy, link, link text and cookieName. 
Banner for upcoming upgrade https://app.clickup.com/t/8688wm6g1
Supports multiple banners at a time

Banner for upcoming upgrade

---

src/App.vue
src/components/FilesTable/FilesTable.vue
src/components/datasets/files/BfDatasetFiles.vue
src/components/datasets/files/RunAnalysisDialog/RunAnalysisDialog.vue
src/components/shared/bf-button/BfButton.vue
src/store/analysisModule.js
src/store/index.js

Deployment PR for the New Run Analysis Workflow - select release just for IH and Pennsieve Test Orgs
https://github.com/Pennsieve/pennsieve-app/releases/tag/v33.6.0

Deployment v33.6.0 - New Run Analysis Flow for App Store

---

src/App.vue

time for the banner to be removed - downtime is over

removed banner

---

src/components/teams/list/TeamsList.vue

Mostly lint changes - fix for sort is just to add sort direction param to returnSort method - this.sortDirection was previously missing. 
`this.teamsList = this.returnSort(key, this.teams, this.sortDirection);` 
[Pennsieve App: default sort People and Teams to ascending alpha order](https://app.clickup.com/t/868836rwk)

fixed sort order for teams 

---

src/components/welcome/request-survey/RequestSurvey.vue

update required fields for request survey https://app.clickup.com/t/8688x6pjw

update required fields for request survey

---

src/components/shared/PennsieveHeader/PennsieveHeader.vue
src/components/shared/PennsieveHeader/contact-us-dialog/ContactUsDialog.vue
src/router/CreateAccount/CreateAccount.vue

- removed unused props and event handlers
- removed unused event and property bindings
- fix broken 'cancel' button
- fix broken 'contact support' link
[Click up ticket](https://app.clickup.com/t/8688weezv)
Screen recording for the bug fix in local (modified local to display the error message in create account page always, just for recording purposes)
https://github.com/user-attachments/assets/83e5cc1d-6625-4001-8132-8a4e132a9e17

Fix broken links sign up page

---

src/components/FilesTable/FilesTable.vue
src/components/TableMenu/TableMenu.vue
src/components/datasets/files/RunAnalysisDialog/RunAnalysisDialog.vue

Fix issue with deselect on files table
https://app.clickup.com/t/8688ufk9e

removed click to deselect

---

src/App.vue
src/components/shared/AnnouncementBanner/AnnouncementBanner.vue

Add the ability to pass in a prop for the url

add a variable url param

---

src/components/SetupProfile/SetupProfile.vue
src/main.js
src/router/index.js
yarn.lock

Ticket:
https://app.clickup.com/t/86891qxz8
Edits:
Added route to index.js and permission to main.js. Added conditional back into SetupProfile

bug fix for sending invite to dataset for non-user

---

src/components/SetupProfile/SetupProfile.vue

clean up code

---

src/App.vue

**ClickUp Ticket:** [8688wm6g1](https://app.clickup.com/t/8688wm6g1)
Banner for scheduled downtime on August 16th, 2024 at 9 PM EST.

maintenance banner for database upgrade

---

src/components/FinalizeAccount/FinalizeAccount.vue
src/components/SetupFederatedLogin/SetupFederatedLogin.vue
src/components/SetupProfile/SetupProfile.vue
src/components/shared/AnnouncementBanner/AnnouncementBanner.vue
src/router/ResetPassword/ResetPassword.vue

Fix password input field styling
In Setup profile page
In Finalize account page
In reset password page

Fix password field styles

---

src/components/SetupProfile/SetupProfile.vue

https://app.clickup.com/t/8689836c6 Guest User Registration via Dataset Invite is not working
This diff is mostly linting changes which I'd like to keep in, but the substantive change is here: 
https://github.com/Pennsieve/pennsieve-app/pull/142/files#diff-0034f440687f2d0496a97abfc990afe5740cec960574adf0f889a77f7f95ecc7R307
We are now doing a PUT for guest user registration and a POST for new user registration. I also added methods to check if the route is /complete or /accept and comments explaining /complete is for GUEST user registration and /accept is for normal user registration, to add clarity.

update the API call to accomidate guest and new user scenarios

---

package.json
src/components/Integrations/ComputeNodesListItem/ComputeNodesListItem.vue
src/mixins/format-date/index.js
yarn.lock

Ticket: https://app.clickup.com/t/86895twy7
First step in migrating over to dat fns from moment js
Description:
Use date-fns instead of moment for analysis tab under compute-nodes section. 
new function added to format date mixin

Feature date fns

---

src/store/uploadModule.js

TICKET: https://app.clickup.com/t/8689kq4ug
FIX: Check to make sure dataset is the same before reusing manifestNodeId

add checker for same datasetid in order to repeat moduleid

---

README.md
src/store/uploadModule.js

ClickUp Ticket:  [User Support] [User reported Duplicated and Misplaced Files when Uploading using the Pennsieve Web App](https://app.clickup.com/t/8689kq4ug) [Platform Bugs]

Prod Deployment: [User Support] User reported Duplicated and Misplaced Files when Uploading using the Pennsieve Web App [Platform Bugs]

---

src/App.vue
src/components/datasets/management/ConceptManagement/ConceptManagement.vue
src/components/datasets/management/GraphManagement/ConceptListItem/ConceptListItem.vue
src/components/datasets/management/GraphManagement/Models.vue
src/components/datasets/records/GraphBrowser/CreateLinkedPropDialog.vue
src/components/datasets/records/GraphBrowser/GraphBrowse2.vue
src/components/datasets/records/GraphBrowser/ModelNode.vue
src/mixins/request/request_composable.js

* Allow users to create linked properties by dragging connections between nodes.
https://github.com/user-attachments/assets/2a508aea-2935-4ab4-ad6d-ba684334d18d

support creating linked properties

---

package-lock.json
package.json
src/assets/_vueflow_core.scss
src/components/datasets/explore/ModelTooltip/ModelTooltip.vue
src/components/datasets/records/GraphBrowser/CreateLinkedPropDialog.vue
src/components/datasets/records/GraphBrowser/GraphBrowse2.vue
src/components/datasets/records/GraphBrowser/ModelDetails.vue
src/components/datasets/records/GraphBrowser/ModelNode.vue
src/components/datasets/records/GraphBrowser/SidePanel.vue
src/components/datasets/records/GraphBrowser/modelInfoPanel.vue
src/components/datasets/records/GraphBrowser/useLayout.js
src/mixins/request/request_composable.js
yarn.lock

* Added multiple tabs to side-panel.
* Added support for relationships

sidepanel updates

---

src/store/uploadModule.js

- fixed upload progress bar indicating wrong total
- user support ticket - https://app.clickup.com/t/86891ckb8
Recording: Before fix
https://github.com/user-attachments/assets/c9f4dea8-ef2f-47c6-8492-c9710d34b95c
Recording: After fix
https://github.com/user-attachments/assets/ce8a908a-cfb6-4edb-b398-62c24d1f5359

fix upload progress banner defect

---

src/components/datasets/records/GraphBrowser/GraphBrowse2.vue
src/components/datasets/records/GraphBrowser/SidePanel.vue

* use v-show instead of v-if to fix transition bug

fix render issue by using v-show

---

src/components/datasets/records/GraphBrowser/ModelDetails.vue

* Adding empty state when no models are selected.

empty state

---

src/assets/_base.scss
src/assets/components/_el-popover.scss
src/components/datasets/records/GraphBrowser/AddEditModelProperty.vue
src/components/datasets/records/GraphBrowser/DeleteLinkedPropDialog.vue
src/components/datasets/records/GraphBrowser/DeleteModelDialog.vue
src/components/datasets/records/GraphBrowser/DeletePropertyDialog.vue
src/components/datasets/records/GraphBrowser/DeleteRelationshipDialog.vue
src/components/datasets/records/GraphBrowser/GraphBrowse2.vue
src/components/datasets/records/GraphBrowser/ModelDetails.vue
src/components/datasets/records/GraphBrowser/SidePanel.vue
src/components/datasets/records/ModelsList/ModelsList.vue
src/components/shared/EnumList/EnumList.vue
src/mixins/request/request_composable.js
src/router/Dataset/DatasetMetadataHeader.vue
src/router/index.js
src/store/metadataModule.js

* Added all functionality to full manage schema creation to page
* Removed routes to old pages 
Note: I did not actually remove the code for the old pages, we should do this.

full functionality of schema page

---

src/assets/_base.scss
src/assets/components/_el-popover.scss
src/components/datasets/records/GraphBrowser/AddEditModelProperty.vue
src/components/datasets/records/GraphBrowser/CreateLinkedPropDialog.vue
src/components/datasets/records/GraphBrowser/DeleteLinkedPropDialog.vue
src/components/datasets/records/GraphBrowser/DeleteModelDialog.vue
src/components/datasets/records/GraphBrowser/DeletePropertyDialog.vue
src/components/datasets/records/GraphBrowser/DeleteRelationshipDialog.vue
src/components/datasets/records/GraphBrowser/GraphBrowse2.vue
src/components/datasets/records/GraphBrowser/ModelDetails.vue
src/components/datasets/records/GraphBrowser/SidePanel.vue
src/components/datasets/records/ModelsList/ModelsList.vue
src/components/shared/EnumList/EnumList.vue
src/mixins/request/request_composable.js
src/router/Dataset/DatasetMetadataHeader.vue
src/router/index.js
src/store/metadataModule.js

* Updated Schema Manager
* Remove old model, and relationship panels.

New Schema Manager

---

src/components/Code/ConfigureRepo.vue
src/components/Code/RepoListItem.vue
src/router/index.js
src/store/codeReposModule.js
yarn.lock

- implement api integration in code repos config page
- [`Configure Repos View [FE: Code Repos] `](https://app.clickup.com/t/8689guvq7)
-recording
https://github.com/user-attachments/assets/b8b39564-03d0-43fa-8f9f-6dd2cf9f3dac

implement api integration in code repos config page

---

src/components/datasets/DatasetOverview/DatasetOverview.vue
src/components/icons/IconCopyDocument.vue

Add option to quickly retrieve dataset Node ID https://app.clickup.com/t/86880yx7v

Deployment PR: Copy Dataset Node

---

src/components/datasets/files/BfDatasetFiles.vue

- fix bug causing duplicate api calls to /packages endpoint while trying to fetch dataset files
- [Get Packages](https://app.clickup.com/t/8688r9ngf)
https://github.com/user-attachments/assets/bb317613-9f8b-44da-9cd9-224b6a5dfac1

Fix remove outdated api calls

---

src/components/datasets/explore/search/ModelRecords.vue
src/components/datasets/records/GraphBrowser/GraphBrowse2.vue
src/components/shared/ps-button-dropdown/PsButtonDropdown.vue

* Fixed edge-case where the model list is not showing in the metadata records tab when users create new models and no records exist.

fix empty state model list

---

src/components/Analysis/Applications/CreateApplicationDialog.vue

Updates to Create Application Form [FE: Pennsieve Analytics]
TICKET: https://app.clickup.com/t/8689eg1cw
Form only changes. Push to dev so that I can confirm form values with team.

updating form to show values cpu and memory

---

src/components/Analysis/Applications/CreateApplicationDialog.vue

TICKET: https://app.clickup.com/t/8689eg1cw

remove commented out code

---

src/main.js
src/site-config/dev.json
src/site-config/local.json
src/site-config/prod.json

* use cookies to store cognito tokens

use cookiestore

---

src/mixins/global-message-handler/index.js

- on logout --> goto the workspaces tab in discover

logout link update

---

src/App.vue
src/components/shared/PennsieveHeader/PennsieveHeader.vue
src/router/CreateAccount/CreateAccount.vue

- Fix sign up error handling
- [Click up task](https://app.clickup.com/t/86899n32a)
Screen recording
https://github.com/user-attachments/assets/d31f82fa-d8a1-4945-b431-7b651f2f180d

upgrade sign up error handling for conflict scenarios

---

src/components/datasets/records/GraphBrowser/GraphBrowse2.vue
src/components/datasets/settings/BfDatasetSettings.vue
src/components/datasets/settings/DatasetSettingsAssociatedPublications/DatasetSettingsAssociatedPublications.vue
src/components/datasets/settings/DatasetSettingsContributors/DatasetSettingsContributors.vue

Contributor async call for url
async call for settings
null handling
stale request popup

Fix publish settings

---

src/store/uploadModule.js

replace old way of getting cognito user auth with amplify fetch
await for target package so users can see the item they are trying to upload

fix for upoloading files to datset

---

src/components/my-settings/MySettingsContainer.vue
src/components/my-settings/windows/CreateApiKey.vue

- resolve API key creation error and rename property for clarity
https://github.com/user-attachments/assets/18c4858c-1c26-4c80-b722-61a586487e04

resolve API key creation error and rename property for clarity

---

src/components/Analysis/ComputeNodes/ComputeNodesList.vue
src/components/datasets/files/RunAnalysisDialog/RunAnalysisDialog.vue
src/store/analysisModule.js

mutations needed to be called to update compute node list

fix run analysis bug

---

src/components/datasets/files/BfDatasetFiles.vue

Correctly trigger for subfolder navigation

fix folder navigation

---

src/components/Code/RepoListItem.vue
src/components/datasets/DatasetActivity/DatasetActivityDetail/DatasetActivityDetail.vue
src/components/datasets/DatasetActivity/DatasetActivityLog.vue
src/components/datasets/DatasetOverview/DatasetOverview.vue
src/components/datasets/dataset-list/BfDatasetList.vue
src/components/datasets/files/BfDatasetFiles.vue
src/components/datasets/files/Metadata/FileMetadataInfo.vue
src/components/datasets/files/RenameFileDialog.vue
src/composables/useSwitchWorkspace.js
src/mixins/request/request_composable.js
src/store/datasetModule.js
src/store/index.js

* fixed readme update
* fixed changelog update
* fixed move file
* fixed rename file
* fixed search
* fixed clear-state on switch org --> missing authors and permissions
* small stylechange to files tab
* fix activity log

Multiple fixes after prod deploy

---

src/components/datasets/settings/DatasetSettingsIgnoreFiles/DatasetSettingsIgnoreFiles.vue
src/router/Datasets/Datasets.vue

Screen recording
https://github.com/user-attachments/assets/07d473f0-6b8e-4da3-8c6f-f4b74f4f1e9c

fix save ignore file names

---

src/components/FilesTable/FilesTable.vue
src/components/datasets/files/Office365Dialog/Office365Dialog.vue

Fix office threesixty

---

README.md
src/components/FilesTable/FilesTable.vue
src/components/viewers/CSVViewer.vue
src/components/viewers/DirectoryViewer.vue
src/components/viewers/ImageViewer.vue
src/components/viewers/TextViewer.vue
src/components/viewers/VideoViewer.vue
src/components/viewers/XLSViewer.vue
src/mixins/static-viewer/index.js

- fix for file preview bug in pennsieve
https://github.com/user-attachments/assets/1febec53-773d-4e82-9247-1f164c46815d

Fix file preview bug

---

src/components/FinalizeAccount/FinalizeAccount.vue
src/router/ResetPassword/ResetPassword.vue

- fix reset password logic with updated API implementation
- removed the auto login functionality as the password reset is complete

fix reset password failure

---

src/components/Analysis/Applications/CreateApplicationDialog.vue

quick fix to previous ticket
TICKET: https://app.clickup.com/t/8689eg1cw
added conversion to memory values in the create application form.

add conversion to memory form

---

src/assets/components/_el-dialog.scss
src/components/Analysis/ActivityLogs.vue
src/components/Analysis/ActivityMonitor.vue
src/store/analysisModule.js
yarn.lock

TICKET: https://app.clickup.com/t/868bun5tz
Activity Logs UI > shows timestamp and message. Loading icon, no logs msg, and no pop-up when there is no processor.

add activity logs to analysis activity page

---

src/components/Analysis/ActivityMonitor.vue
src/components/Analysis/WorkflowsListItem.vue
src/store/analysisModule.js

- add cancel button to analysis workflow
- add confirmation dialog for cancelling workflow
screenshots

Feature add cancel workflow UI

---

src/components/Analysis/Applications/ApplicationsList.vue
src/components/Analysis/ComputeNodes/ComputeNodesList.vue
src/components/bf-navigation/BfNavigation.vue

- fix permissions for displaying action items on analysis pages

Fix permissions to create application

---

src/components/Analysis/Applications/ApplicationsList.vue
src/components/Analysis/Applications/ApplicationsListItem.vue
src/components/datasets/files/RunAnalysisDialog/RunAnalysisDialog.vue

new branch to merge into epic with update changes.

fix to merge into epic

---

src/components/Analysis/WorkflowsListItem.vue
src/store/analysisModule.js

Makes extra call to /status endpoint for each workflow to get the workflow status

Add Failed Status to Workflow List 

---

src/components/Analysis/Applications/ApplicationsList.vue
src/components/Analysis/Applications/ApplicationsListItem.vue

New Ticket: https://app.clickup.com/t/868cd1w0y
add pusher channel and event listener applicationListItem.vue
remove fetch all from deploy functionality.
remove interval and fetch from applicationList.vue
in response to [John's work ](https://github.com/Pennsieve/app-deploy-service/pull/72)

add pusher to applications List Item

---

src/components/Analysis/Applications/ApplicationsList.vue
src/components/Analysis/Applications/ApplicationsListItem.vue

New Ticket: https://app.clickup.com/t/868cd1w0y
add pusher channel and event listener applicationListItem.vue
remove fetch all from deploy functionality.
remove interval and fetch from applicationList.vue
in response to John's work

Analytics pusher

---

src/store/analysisModule.js

[Migrate endpoints to new authorizers (Analytics)](https://app.clickup.com/t/868axnpyw)

Deploy: Add OrgId to GET requests for applications, compute-nodes, workflows/instances and accounts 

---

src/components/Analysis/Applications/ApplicationsListItem.vue
src/components/Analysis/Applications/EditApplicationDialog.vue
src/components/Analysis/ComputeNodes/ComputeNodesListItem.vue
src/components/Analysis/ComputeNodes/EditComputeNodeDialog.vue
src/components/Integrations/IntegrationsListItem/IntegrationsListItem.vue
src/components/Integrations/WebhooksList/WebhooksList.vue
src/components/bf-navigation/BfNavigation.vue
src/components/datasets/files/RunAnalysisDialog/RunAnalysisDialog.vue
src/router/Analysis/Analysis.vue
src/store/analysisModule.js

This PR adds the following functionality: 
-Allow Owners to Delete Compute Nodes
-Allow Admins to Update and Delete Applications
-Messaging (tooltips) to explain permissions 
-Pass Named Workflows 
Associated Tickets:
[FE: Expose Deletion of Applications](https://app.clickup.com/t/868cnrjc0)
[Expose named workflow property](https://app.clickup.com/t/868cq9gmf)
[FE: Expose Deletion of Compute nodes](https://app.clickup.com/t/868cnrjhy)

Updates to Pennsieve Analytics UI Sprint 81

---

src/components/datasets/DatasetOverview/DashboardModal.vue

simple fix from a toString() that was meant to be removed

fix undefined bug on file count

---

src/store/codeReposModule.js

[Frontend: update GitHub service API calls](https://app.clickup.com/t/868bpe264)

Deploy: add org id query to enable, disable, external and publish

---

src/components/FilesTable/FilesTable.vue
src/components/datasets/files/RunAnalysisDialog/RunAnalysisDialog.vue

IH requested the date column on the run analysis file table. I also included the file size column. 
[Clickup](https://app.clickup.com/t/868cuthfv)

Feature update file exporer run analysis

---

src/components/Analysis/Activity/ActivitySidePanel.vue
src/store/analysisModule.js

BUG: Processor selection Toggles All Workflow view unexpectedly
https://app.clickup.com/t/868d8xw4q
Release: https://github.com/Pennsieve/pennsieve-app/releases/tag/v33.19.2

Deploy: Activity Monitor functionality fixes

---

src/components/viewers/TSViewer/TSPlotCanvas.vue
src/components/viewers/TSViewer/TSScrubber.vue
src/store/index.js

- fix typo in for store action
- remove unused code
- add error handling to canvas refs

Fix timeseries viewer runtime error

---

src/mixins/request/index.js

* on 403, only redirect to datasets-list if router initialized

fix for guest app error 

---

src/components/viewers/TSViewer/TSViewerToolbar.vue

- Fix UI defects in tiemeseries viewer toolbar
- https://app.clickup.com/t/868deqz1u
https://github.com/user-attachments/assets/a049afd8-59ab-4edd-b68a-83d9bee69502

fix UI defects

---

src/components/bf-navigation/BfNavigation.vue

Hide Code Repos Tab because we are moving it to the "My Data" portion of the application

hide code tab

---

src/components/datasets/files/BfDatasetFiles.vue
src/store/index.js

- fix file directory navigation bug
Ticket - [[User Support] File explorer bug](https://app.clickup.com/t/868dhf81m)
Recording
https://github.com/user-attachments/assets/68b3f8d8-4e7e-450d-b525-fda6c066af17

Fix file explorer bug

---

src/components/datasets/files/BfDatasetFiles.vue

- removing unnecessary api call for fixing bug and smoother UI transitions

patch to the fix for file explorer bug

---

src/components/viewers/TSViewer/TSFilterModal.vue
src/components/viewers/TSViewer/TSViewer.vue

- fixed timeseries viewer filter feature
Screen recording for the fix -
https://github.com/user-attachments/assets/01466fea-116f-4af6-86a8-61a5fc31a5da

Fix timeseries filter

---

package-lock.json
package.json
yarn.lock

small update to fix add widget bug

update version to fix add widget bug

---

package-lock.json
package.json
src/assets/components/_el-dialog.scss
src/components/datasets/DatasetOverview/DashboardModal.vue
src/components/datasets/DatasetOverview/DatasetOverview.vue
src/main.js

Install Dashboard in main with element plus
Adding Dashboard to Dataset Overview page
Dashboard setup with reactive values populated from Dataset
Overriding dependency style leak from Element-Plus version

Deploy: Dashboard into Overview Page

---

src/utils/feature-flags.js

- add pennsieve test prod org id to orgs list

add pennsieve test prod org id to orgs list

---

src/assets/components/_el-dialog.scss
src/components/datasets/DatasetOverview/DashboardModal.vue

Making the buttons match up more. 
unable to use scoped but assigned via a class, style bleed should not happen.

Prod dashboard

---

src/utils/feature-flags.js

- update correct org id fro 'pennseive prod test' workspace

fix org id

---

src/components/datasets/DatasetOverview/DatasetOverview.vue
src/components/datasets/dataset-list/dataset-list-item/BfDatasetListItem.vue

TICKET: https://app.clickup.com/t/868cjy3x1
Add back DOI to dataset overview
this lead to larger bug find ticket here: https://app.clickup.com/t/868ctgn9t

Fix doi clean

---

src/components/datasets/DatasetPermissions/AddPermissionForm/AddPermissionForm.vue

- fix styling - update input box width
fix

update css for permissions page

---

src/components/Analysis/Applications/DeleteApplicationDialog.vue
src/components/datasets/explore/ConceptInstance/ConceptInstancePropertyInput.vue
src/components/viewer/MontageErrorDialog/MontageErrorDialog.vue
src/components/viewer/PsViewer/PsViewer.vue
src/components/viewers/TSViewer/TSViewer.vue
src/components/viewers/TSViewer/TSViewerToolbar.vue
src/store/index.js

- update timeseries viewer montaging error handling to display error dialog
Screen recording:
https://github.com/user-attachments/assets/75dd289c-c231-4222-8a5a-5a0e15339d5a

Fix timeseries montaging

---

src/components/Analysis/Applications/DeleteApplicationDialog.vue
src/components/datasets/explore/ConceptInstance/ConceptInstancePropertyInput.vue
src/components/viewer/MontageErrorDialog/MontageErrorDialog.vue
src/components/viewer/PsViewer/PsViewer.vue
src/components/viewers/TSViewer/TSViewer.vue
src/components/viewers/TSViewer/TSViewerToolbar.vue
src/store/index.js

- update timeseries viewer montaging error handling to display error dialog
Screen recording:
https://github.com/user-attachments/assets/75dd289c-c231-4222-8a5a-5a0e15339d5a

Deploy: Fix timeseries montaging

---

src/components/viewers/TSViewer/TSPlotCanvas.vue

Updating Viewer to support notion that server drops messages (requested pages).
This supports the updated streaming service which drops old requests if newer requests are available.

Feature ts assume dropped messages

---

src/components/viewers/TSViewer/TSPlotCanvas.vue

* draw line through max values for better visibility

draw line through max values for better visibility

---

src/components/viewers/TSViewer/TSPlotCanvas.vue

* small fix for ids for labels in montages and ordering

fix_montage_ids

---

src/components/viewers/TSViewer/TSPlotCanvas.vue
src/components/viewers/TSViewer/TSViewer.vue
src/components/viewers/TSViewer/TSViewerCanvas.vue

* Refactored logic to separate expected id's locally, and server-side during montaging.

updated logic to handle virtual channels during montage

---

src/components/SetupFederatedLogin/SetupFederatedLogin.vue
src/components/viewers/TSViewer/TSCustomMontageDialog.vue
src/components/viewers/TSViewer/TSPlotCanvas.vue
src/components/viewers/TSViewer/TSViewer.vue
src/components/viewers/TSViewer/TSViewerCanvas.vue
src/components/viewers/TSViewer/TsCreateMontageDialog.vue

* Send virtual channel IDs when requesting filter 
* Removed unnecessary console.log statements

Send virtual channel ids on filter request

---

package-lock.json
package.json
src/components/datasets/DatasetPermissions/AddPermissionForm/AddPermissionForm.vue
src/components/datasets/collaborators/ConfirmRoleDialog/ConfirmRoleDialog.vue
src/components/datasets/collaborators/DatasetCollaborator/DatasetCollaborator.vue
src/composables/useHighlightText.js
src/composables/useSorter.js
src/mixins/global-message-handler/index.js

Troubleshoot permissions error 2

---

package-lock.json
package.json
src/components/Analysis/Activity/ActivityMonitor.vue
src/components/datasets/records/GraphBrowser/GraphBrowse2.vue
src/components/viewers/TSViewer/TSPlotCanvas.vue
src/components/viewers/TSViewer/TSViewer.vue
src/components/viewers/TSViewer/TSViewerToolbar.vue
vite.config.js

1) Updated timeseries viewer to have better selectors for vertical and horizontal scale
2) Updated sass and elements-plus version
I needed to update element-plus and sass to get the correct version of the element-plus numeric-input components

timeseries updates and SASS

---

package-lock.json
package.json
src/components/shared/bf-button/BfButton.vue
src/components/viewer/ViewerPane/ViewerPane.vue
src/components/viewers/DuckDBExplorer/DuckDBViewerWrapper.vue
src/components/viewers/DuckDBExplorer/dbduckViewer.vue
src/components/viewers/UmapViewer/scatterplot.vue
src/components/viewers/UmapViewer/wrapper.vue
src/mixins/FileTypeMapper/index.js

* Adding DuckDB query viewer for 
a) parquet files
b) CSV files

added duckdb viewer

---

src/components/welcome/SubmitDatasets.vue

- fix styling defect in dataset proposals page

fix dialog styling dataset proposals

---

package-lock.json
package.json
src/components/datasets/metadata/models/CreateRecord.vue
src/components/datasets/metadata/models/ListRecords.vue
src/components/datasets/metadata/models/ModelRecordsSelector.vue
src/components/datasets/metadata/models/ModelSelectorDialog.vue
src/components/datasets/metadata/models/ModelSpecViewer.vue
src/components/datasets/metadata/models/RecordSpecViewer.vue
src/components/datasets/metadata/models/TemplateSpecViewer.vue
src/components/shared/ViewToggle/ViewToggle.vue
src/router/Dataset/DatasetMetadataHeader.vue
src/router/index.js
src/stores/metadataStore.js
src/styles/_theme.scss
vite.config.js

Model management

---

package-lock.json
package.json
src/components/datasets/DatasetOverview/DashboardModal.vue
src/main.js

Reverts Pennsieve/pennsieve-app#432

Revert "Feature update dash"

---

package-lock.json
package.json
src/components/datasets/DatasetOverview/DashboardModal.vue
src/main.js

github not recognizing changes in the package.json or lock

Feature update dash

---

package-lock.json
package.json
src/components/datasets/DatasetOverview/DashboardModal.vue
src/main.js

TICKET: https://app.clickup.com/t/868fq7eue
migrate to latest dashboard
add element plus to all (needed for dependencies to be applied)
remove old dashboard

Feature update dash main
